### PR TITLE
Add Brave Browser to supported browser list

### PR DESCRIPTION
**Pull request by bbondy**

### CODE REVIEW

**Comment by hoshsadiq** [comment]
Hi, thanks for PR. What exactly do you mean by "Included by default"?

**Comment by bbondy** [comment]
Users will not have to add it manually

**Comment by hoshsadiq** [comment]
Do you mean the list is included by default?

**Comment by bbondy** [comment]
Yes it is included by default and turned on by default.

**Comment by hoshsadiq** [comment]
Aah okay. Cool. Thanks!

**Pull request merged**
