### PR TITLE
Sync with "resource abuse" filter list

### PR DESCRIPTION
**Pull request by SMed79**
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt

### CODE REVIEW

**Comment by SMed79** [comment]
@okiehsch Please check for there is any error.

**Comment by okiehsch** [comment]
`*$csp` but that is not essential, uBO will interprete your filter that way.

**Comment by SMed79** [comment]
Thank you.

**Comment by hoshsadiq** [comment]
Thanks!

**Pull request merged**
