### PR TITLE
Update hosts.txt

### PR DESCRIPTION
**Pull request by cronlabspl**
Fix small typo

### CODE REVIEW

**Comment by smed79** [comment]
It's not a typo https://github.com/hoshsadiq/adblock-nocoin-list/commit/4ef5cb3397fe476b0fcb3e80ee8cc9b269868133

**Comment by cronlabspl** [comment]
> It's not a typo [4ef5cb3](https://github.com/hoshsadiq/adblock-nocoin-list/commit/4ef5cb3397fe476b0fcb3e80ee8cc9b269868133)

Seriously? 
Zrzut ekranu 2021-12-21 o 16 58 14

**Comment by hoshsadiq** [comment]
@cronlabspl it used to be a thing, it probably doesn't exist any more. coin-hive.com is already in the list.

**Comment by smed79** [comment]
`coin-have.com` is alive ...
coin-have com

**Comment by cronlabspl** [comment]
> `coin-have.com` is alive ...
> 
> coin-have com

Your screen proves that **domain exists** and thats true; but it **does not** point to correct web.

**Pull request closed without merging**
