### PR TITLE
Added minemytraffic

### PR DESCRIPTION
**Pull request by ewasion**

### CODE REVIEW

**Comment by SMed79** [comment]
@ewasion `minemytraffic.com` redirect to a suspended page http://i.imgur.com/bueu94Q.png
Before merging this PR the maintainer need an example sites where we can see minemytraffic in acction.

**Comment by crssi** [comment]
its not suspended anymore and it is live

**Comment by ewasion** [comment]
The script is located here https://minemytraffic.com/lib/xminer.min.js

**Comment by hoshsadiq** [comment]
Thanks!

**Pull request merged**
