### PR TITLE
Update hosts.txt

### PR DESCRIPTION
**Pull request by callmenemo491**
added podrltid.info #26  +sorted list alphabetically.

### CODE REVIEW

**Comment by SMed79** [comment]
@hoshsadiq 
I suggest to stop adding these random domains because this is not effective with the "[hosts file](https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt)" and already fixed in "[nocoin list](https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt)" by the filter `.info^$script,domain=...`

@callmenemo491 
Not need to sort the list. We shoold keep these random domains in the same category to keep the list clear and clean.

**Comment by hoshsadiq** [comment]
Yeah, I have to agree. It'll just become a cat and mouse game. No point. I will remove them from the list as well,. The filter list is good enough to me. By the way, I don't see the filter being blocked on uBlock Origin on those domains

**Comment by SMed79** [comment]
> I don't see the filter being blocked

e.g.
- On oload.tv ==> http://i.imgur.com/8gGGdIQ.png
- On openload.co it's blocked by the generic filter in [easylist](https://easylist-downloads.adblockplus.org/easylist.txt) added for popads 
`$script,third-party,domain=...`

**Comment by hoshsadiq** [comment]
Aah I see. I must be blind

**Pull request closed without merging**
