### PR TITLE
Fix for blocking windscribe.com

### PR DESCRIPTION
**Pull request by arkblame**

### CODE REVIEW

**Comment by smed79** [comment]
Why `windscribe.com` should be blocked ?

**Comment by hoshsadiq** [comment]
I think probably a competitor. Created the account and raised this PR.

**Comment by arkblame** [comment]
I've made a mistake, maybe not whole site but https://windscribe.com/miner should be.

**Comment by hoshsadiq** [comment]
They are using CoinHive which is already in the blocked from starting any mining processes (and mining does not start when only this list is enabled). If you believe that the page is able to start a process, let us know and we can investigate.

**Comment by smed79** [comment]
@arkblame Does `windscribe` force you to go to the mining page?

**Pull request closed without merging**
