### PR TITLE
Added kisshentai.net (nsfw)

### PR DESCRIPTION
**Pull request by SMed79**

### CODE REVIEW

**Comment by hoshsadiq** [comment]
Do we need this? The js will be loaded, but the websockets won't run as they are still running on `coin-hive.com`, which in turn will be blocked by the `$third-party` block.

**Comment by SMed79** [comment]
It's logical.

**Comment by hoshsadiq** [comment]
Can you reopen it so I can merge after all? Just cos it means no need to unnecessarily download additional files

**Comment by hoshsadiq** [comment]
Thank you!

**Pull request merged**
