### PR TITLE
Added 'hashforcash.us' and 'coin-have.com'

### PR DESCRIPTION
**Pull request by Shaa3**
Added 2 domains to hosts.txt and nocoin.txt

### CODE REVIEW

**Comment by SMed79** [comment]
Do you have an example for `hashforcash.us`?

**Comment by hoshsadiq** [comment]
Yes, I'd like to see examples for both hashforcash and coin-have. I don't see any JavaScript or mining on their websites.

**Comment by Shaa3** [comment]
I saw no websites that use coin-have.com yet. I had one site that used hashforcash. I'll see if I can find it again.

**Comment by hoshsadiq** [comment]
Sorry, don't necessarily need a website, the actual JS works too. I can have a look at the JS and check what's necessary to block.

**Comment by hoshsadiq** [comment]
Found coin-have.com's javascript by registering with a fake account. Have added coin-have. But still don't see anything regarding hashforcash.

**Comment by hoshsadiq** [comment]
@Shaa3 any updates? If not I will close this PR.

**Pull request closed without merging**
