### PR TITLE
Fix deltabit.co

### PR DESCRIPTION
**Pull request by SMed79**
For details see https://github.com/hoshsadiq/adblock-nocoin-list/pull/206

### CODE REVIEW

**Comment by SMed79** [comment]
@ryanbr popads + mining.

**Comment by robymontyz** [comment]
Thanks for the fixes!

Can you also add `cryptonoter.com` as said [here](https://github.com/hoshsadiq/adblock-nocoin-list/pull/206#issuecomment-382911846)? 

https://github.com/SMed79/adblock-nocoin-list/blob/7f4eb97dedaaf3339ade0fa5fdd5129d52488131/nocoin.txt#L184
Also, can you explain me what `^$third-party` does and why is it better than the full URL? 😁

**Comment by SMed79** [comment]
> Can you also add cryptonoter.com

Already there https://github.com/hoshsadiq/adblock-nocoin-list/search?q=cryptonoter.com&type=Code

> can you explain me what ^$third-party 

If the `third-party` option is specified, the filter is only applied to requests from a different origin than the currently viewed page.
Adblock Plus filters syntax https://adblockplus.org/en/filters.

**Comment by robymontyz** [comment]
> Already there 

Oh sorry, probably @hoshsadiq didn't noticed that.

> If the third-party option is specified, the filter is only applied to requests from a different origin than the currently viewed page.
Adblock Plus filters syntax https://adblockplus.org/en/filters.

Thanks for the explanation and the reference!

**Comment by SMed79** [comment]
> probably @hoshsadiq didn't noticed that

He tried to tell you to take `||cryptonoter.com^$third-party` as an example to update your filter. 

@hoshsadiq I will let you add these mirror domains https://github.com/easylist/easylist/commit/643bf1fc2b33c752

**Comment by hoshsadiq** [comment]
Aah my bad, I did mean to add cryptonoter, but didn't realise it was on there already.

@SMed79 I'll add those domains.

**Pull request merged**
