### PR TITLE
Added bablace.com

### PR DESCRIPTION
**Pull request by jacekoleksy**
This is a fix for https://github.com/hoshsadiq/adblock-nocoin-list/issues/92

### CODE REVIEW

**Comment by mapx-** [comment]
better `||bablace.com^`

(however it's an error `thirdparty` has to be `third-party`)

**Comment by jacekoleksy** [comment]
Indeed, there is a typo, will fix. But why not third-party?

**Comment by hoshsadiq** [comment]
Thank you

@mapx- quick question, what's the difference?

**Comment by jacekoleksy** [comment]
From https://adblockplus.org/filters:

"Restriction to third-party/first-party requests: If the third-party option is specified, the filter is only applied to requests from a different origin than the currently viewed page. Similarly, ~third-party restricts the filter to requests from the same origin as the currently viewed page."

Requests to bablace.com will not be blocked if we are on bablace.com webpage, but I think that is intended.

**Comment by mapx-** [comment]
`bablace` is not a real site (with a home page .. you'll get `Cannot GET /` visiting it) so is not necessary `third-party` but it's not a mistake

**Comment by hoshsadiq** [comment]
Aah good to know. There's many other sites like that. I will try and update them this evening.

**Comment by SMed79** [comment]
add also `||sparnove.com^` and `0.0.0.0 sparnove.com`

* http\://sparnove.com/2832012445a39841.2.n.2.1.js

**Comment by hoshsadiq** [comment]
Added!

**Pull request merged**
