### PR TITLE
Added baiduccdn1.com to the ban list

### PR DESCRIPTION
**Pull request by St-Fl**
The site https://baiduccdn1.com/lib/cryptonight.wasm is containing a crypto miner.

### CODE REVIEW

**Comment by hoshsadiq** [comment]
I have a feeling this will block a lot more than just the miner. Have you tested this? It looks like this is on a cdn from baidu which may block other assets.

Also, could you add it to the nocoin.txt file too?

**Comment by ZeroDot1** [comment]
@hoshsadiq This is not a Baidu domain.
```
$ whois baiduccdn1.com
   Domain Name: BAIDUCCDN1.COM
   Registry Domain ID: 2097116811_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.internet.bs
   Registrar URL: http://www.internet.bs
   Updated Date: 2017-02-12T00:06:20Z
   Creation Date: 2017-02-12T00:06:19Z
   Registry Expiry Date: 2018-02-12T00:06:19Z
   Registrar: Internet Domain Service BS Corp
   Registrar IANA ID: 2487
   Registrar Abuse Contact Email:
   Registrar Abuse Contact Phone:
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: JUNE.NS.CLOUDFLARE.COM
   Name Server: RICK.NS.CLOUDFLARE.COM
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2017-12-11T14:57:11Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

NOTICE: The expiration date displayed in this record is the date the
registrar's sponsorship of the domain name registration in the registry is
currently set to expire. This date does not necessarily reflect the expiration
date of the domain name registrant's agreement with the sponsoring
registrar.  Users may consult the sponsoring registrar's Whois database to
view the registrar's reported date of expiration for this registration.

TERMS OF USE: You are not authorized to access or query our Whois
database through the use of electronic processes that are high-volume and
automated except as reasonably necessary to register domain names or
modify existing registrations; the Data in VeriSign Global Registry
Services' ("VeriSign") Whois database is provided by VeriSign for
information purposes only, and to assist persons in obtaining information
about or related to a domain name registration record. VeriSign does not
guarantee its accuracy. By submitting a Whois query, you agree to abide
by the following terms of use: You agree that you may use this Data only
for lawful purposes and that under no circumstances will you use this Data
to: (1) allow, enable, or otherwise support the transmission of mass
unsolicited, commercial advertising or solicitations via e-mail, telephone,
or facsimile; or (2) enable high volume, automated, electronic processes
that apply to VeriSign (or its computer systems). The compilation,
repackaging, dissemination or other use of this Data is expressly
prohibited without the prior written consent of VeriSign. You agree not to
use electronic processes that are automated and high-volume to access or
query the Whois database except as reasonably necessary to register
domain names or modify existing registrations. VeriSign reserves the right
to restrict your access to the Whois database in its sole discretion to ensure
operational stability.  VeriSign may restrict or terminate your access to the
Whois database for failure to abide by these terms of use. VeriSign
reserves the right to modify these terms at any time.

The Registry database contains ONLY .COM, .NET, .EDU domains and
Registrars.
Domain Name: BAIDUCCDN1.COM
Registry Domain ID: 2097116811_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.internet.bs
Registrar URL: http://www.internetbs.net
Updated Date: 2017-02-12T00:06:20Z
Creation Date: 2017-02-12T00:06:19Z
Registrar Registration Expiration Date: 2018-02-12T00:06:19Z
Registrar: Internet Domain Service BS Corp.
Registrar IANA ID: 2487
Registrar Abuse Contact Email: abuse@internet.bs
Registrar Abuse Contact Phone: +1.5167401179
Reseller: 
Domain Status: clientTransferProhibited - http://www.icann.org/epp#clientTransferProhibited
Registry Registrant ID: 
Registrant Name: Domain Admin
Registrant Organization: Whois Privacy Corp.
Registrant Street: Ocean Centre, Montagu Foreshore, East Bay Street
Registrant City: Nassau
Registrant State/Province: New Providence
Registrant Postal Code: 
Registrant Country: BS
Registrant Phone: +1.5163872248
Registrant Phone Ext: 
Registrant Fax: 
Registrant Fax Ext: 
Registrant Email: baiduccdn1.com-owner-yqvw@customers.whoisprivacycorp.com
Registry Admin ID: 
Admin Name: Domain Admin
Admin Organization: Whois Privacy Corp.
Admin Street: Ocean Centre, Montagu Foreshore, East Bay Street
Admin City: Nassau
Admin State/Province: New Providence
Admin Postal Code: 
Admin Country: BS
Admin Phone: +1.5163872248
Admin Phone Ext: 
Admin Fax: 
Admin Fax Ext: 
Admin Email: baiduccdn1.com-admin-nzsh@customers.whoisprivacycorp.com
Registry Tech ID: 
Tech Name: Domain Admin
Tech Organization: Whois Privacy Corp.
Tech Street: Ocean Centre, Montagu Foreshore, East Bay Street
Tech City: Nassau
Tech State/Province: New Providence
Tech Postal Code: 
Tech Country: BS
Tech Phone: +1.5163872248
Tech Phone Ext: 
Tech Fax: 
Tech Fax Ext: 
Tech Email: baiduccdn1.com-tech-afsx@customers.whoisprivacycorp.com
Name Server: june.ns.cloudflare.com
Name Server: rick.ns.cloudflare.com
DNSSEC: unsigned
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/
>>> Last update of WHOIS database: 2017-12-11T14:53:33Z <<<

```

**Comment by St-Fl** [comment]
Thanks ZeroDot1 for the comment and lookup.

@hoshsadiq: I added also the nocoin.txt. Let me know if you need anything else. For me the URL I put in looks like maleware.

Cheers
Stefan

**Comment by hoshsadiq** [comment]
@ZeroDot1 my bad! Thanks for the heads.

**Pull request merged**
