### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ignoramous**
Add RethinkDNS which natively supports the NoCoin list.

Ref: https://rethinkdns.com/configure#1:ABAAAg==

### CODE REVIEW

**Comment by smed79** [comment]
Thank you but sorry no, we are not going to index all adblockers on our readme.

**Comment by ignoramous** [comment]
@smed79 

Disappointing. Here are my thoughts:

cc: @hoshsadiq 

RethinkDNS is only one of two (the other being [getintra.org](https://getintra.org)) userspace DNS Clients on Android that do not leak queries over TCP.

This is a NoCoin trackers list, and crypto miners  are no slouches. They can defeat the list by simply opting to send DNS queries over TCP and none of the current open source DNS clients listed for Android are capable of handling that.

Besides RethinkDNS also support _anonymous_ DNS queries over `DNSCrypt v3`, which none of the listed content blocking DNS clients are capable of doing.

Since RethinkDNS sees all traffic on a phone (local recursive VPN), which none of the current DNS clients on Android can do, it can also prevent bypasses where the app may use its own DoH to resolve IPs and hence bypassing the traditional DNS-only clients, but they can escape RethinkDNS.  

How does it do so when other clients won't / can't? RethinkDNS can block traffic to all IPs that it itself did not resolve.

**Comment by smed79** [comment]
who is next to add ... [personalDNSfilter](https://www.zenz-solutions.de/personaldnsfilter-wp/) ?

I will let @hoshsadiq decide what to do.

**Comment by hoshsadiq** [comment]
@ignoramous I totally appreciate that your app might be the best in it's class. This isn't about that. This project isn't about indexing all DNS blockers, it's about indexing, or blocking, as many of crypto miners, especially the ones that mine without user consent.

I naïvely added many options in the beginning of starting this, but it just doesn't make sense to add every possible blocker.

Quite frankly I've been thinking of deprecating hosts.txt because it's just not been as up to date as the adblock rules.

Anyway, for these reasons, @smed79 made the right decision.

**Comment by ignoramous** [comment]
Makes sense. Thanks for your explanation.

Not my place, but here's my 2 cents:

When I think about it, users who stumble upon blocklists do want to know how and where to use them. If I don't have it in the readme, it needs to be somewhere else accessible.

A content-blocker is better for having preset blocklists built-in (like how rethinkdns bundles in NoCoin, for example; and Firefox bundles disconnect.me lists), otherwise it is just useless to most who seek convenience over configuration.

Anyways, your call to make.

**Pull request closed without merging**
