### PR TITLE
Fix + Sort

### PR DESCRIPTION
**Pull request by SMed79**
No need to block the 1st part contents.

### CODE REVIEW

**Comment by hoshsadiq** [comment]
Reason I didn't make `miner.pr0gramm.com` third-party is because as soon as you jump on the website, it starts mining. It doesn't let you choose to start (unlike coin-hive.com). What do you think of the following?
```||miner.pr0gramm.com/cryptonight-worker.wasm
||miner.pr0gramm.com:8044
||miner.pr0gramm.com/cryptonight-worker.js
||miner.pr0gramm.com/xmr.min.js
```

**Comment by SMed79** [comment]
I think I need to change:

```
||miner.pr0gramm.com^$third-party
```
to:
```
||miner.pr0gramm.com^$websocket
||miner.pr0gramm.com/cryptonight-worker.js
||pr0gramm.com/api/
```
@gorhill do you confirm?

**Comment by hoshsadiq** [comment]
I think that works, but just append it, don't change it so that third party is also blocked.

**Comment by hoshsadiq** [comment]
I've merged, will add those extra rules

**Pull request merged**
